configfile: "config/project.yaml"

from pathlib import Path
from af3custom.targets import get_proteins, get_pairs

# -------------------------
# SETUP
# -------------------------

proteins = get_proteins(config)
protein_names = sorted(proteins.keys())

MONO_JSON_DIR = config["paths"]["monomer_json_dir"]
MULTI_JSON_DIR = config["paths"]["multimer_json_dir"]
PIPELINE_DIR = config["paths"]["json_pipeline_dir"]
RESULTS_DIR = config["paths"]["results_dir"]

MODE = config["workflow"]["mode"]

if MODE == "multimer":
    pairs = get_pairs(config, proteins)
    pair_names = [f"{p1}__{p2}" for p1, p2 in pairs]

# -------------------------
# TARGETS
# -------------------------

if MODE == "monomer":
    final_targets = expand(f"{RESULTS_DIR}/{{name}}", name=protein_names)

elif MODE == "multimer":
    final_targets = expand(f"{RESULTS_DIR}/{{name}}", name=pair_names)

else:
    raise ValueError(f"Unknown mode: {MODE}")

rule all:
    input:
        final_targets

# -------------------------
# STEP 1: MONOMER JSON
# -------------------------

rule make_monomer_json:
    input:
        fasta=lambda wc: proteins[wc.name]
    output:
        json=f"{MONO_JSON_DIR}/{{name}}.json"
    resources:
        partition="short",
        mem_mb=2000,
        time="00:10:00",
        cpus=1
    run:
        from af3custom.monomer_json_builder import write_monomer_json
        Path(MONO_JSON_DIR).mkdir(parents=True, exist_ok=True)
        write_monomer_json(wildcards.name, input.fasta, MONO_JSON_DIR)

# -------------------------
# STEP 2: DATA PIPELINE
# -------------------------

rule data_pipeline:
    threads: config["resources"]["data_pipeline"]["cpus"]
    resources:
        partition=config["resources"]["data_pipeline"]["partition"],
        mem_mb=config["resources"]["data_pipeline"]["mem_mb"],
        time=config["resources"]["data_pipeline"]["time"]
    input:
        json=f"{MONO_JSON_DIR}/{{name}}.json"
    output:
        outdir=directory(f"{PIPELINE_DIR}/{{name}}")
    log:
        "logs/data_pipeline/{name}.log"
    params:
        image=config["af3"]["image"],
        db_dir=config["af3"]["db_dir"]
    shell:
        r"""
        mkdir -p {output.outdir}
        mkdir -p logs/data_pipeline

        /usr/bin/time -v \
        singularity exec \
            --bind {params.db_dir}:/root/public_databases \
            --bind {output.outdir}:/root/af_output \
            --bind {MONO_JSON_DIR}:/root/af_input \
            {params.image} \
            python3 /app/alphafold/run_alphafold.py \
            --json_path=/root/af_input/{wildcards.name}.json \
            --db_dir=/root/public_databases \
            --output_dir=/root/af_output \
            --run_data_pipeline=true \
            --run_inference=false \
        &> {log}
        """

# -------------------------
# STEP 3: MULTIMER JSON
# -------------------------

rule build_multimer_json:
    input:
        p1=lambda wc: f"{PIPELINE_DIR}/{wc.name.split('__')[0]}",
        p2=lambda wc: f"{PIPELINE_DIR}/{wc.name.split('__')[1]}"
    output:
        json=f"{MULTI_JSON_DIR}/{{name}}.json"
    resources:
        cpus=1
    run:
        from af3custom.multimer_json_builder import build_single_multimer_json
        Path(MULTI_JSON_DIR).mkdir(parents=True, exist_ok=True)
        p1, p2 = wildcards.name.split("__")
        build_single_multimer_json(config, p1, p2)

# -------------------------
# STEP 4: INFERENCE
# -------------------------

def get_input_json(wildcards):
    if MODE == "monomer":
        return f"{MONO_JSON_DIR}/{wildcards.name}.json"
    else:
        return f"{MULTI_JSON_DIR}/{wildcards.name}.json"

rule run_inference:
    threads: config["resources"]["inference"]["cpus"]
    resources:
        partition=config["resources"]["inference"]["partition"],
        mem_mb=config["resources"]["inference"]["mem_mb"],
        time=config["resources"]["inference"]["time"],
        gres=config["resources"]["inference"]["gres"]
    input:
        json=get_input_json
    output:
        outdir=directory(f"{RESULTS_DIR}/{{name}}")
    log:
        "logs/inference/{name}.log"
    params:
        image=config["af3"]["image"],
        db_dir=config["af3"]["db_dir"],
        model_dir=config["af3"]["model_dir"]
    shell:
        r"""
        mkdir -p {output.outdir}
        mkdir -p logs/inference

        /usr/bin/time -v \
        singularity exec \
            --nv \
            --env JAX_PLATFORMS=cuda \
            --bind {params.db_dir}:/root/public_databases \
            --bind {params.model_dir}:/root/models \
            --bind {output.outdir}:/root/af_output \
            --bind work/json:/root/af_input \
            {params.image} \
            python3 /app/alphafold/run_alphafold.py \
            --json_path=/root/af_input/{wildcards.name}.json \
            --model_dir=/root/models \
            --db_dir=/root/public_databases \
            --output_dir=/root/af_output \
            --run_data_pipeline=false \
            --run_inference=true \
        &> {log}
        """