af3:
  image: /data/dops-plant-genomics/lady8018/af3/containers/alphafold3_custom.sif
  model_dir: /apps/common/commercial/AlphaFold3/model
  db_dir: /apps/datasets/alphafold3/public_databases

paths:
  fasta_root: inputs/fastas
  monomer_json_dir: work/json/monomers
  multimer_json_dir: work/json/multimers
  json_pipeline_dir: work/json/pipeline
  results_dir: outputs

workflow:
  # Workflow modes:
  # monomer  → FASTA → pipeline → inference
  # multimer → FASTA → pipeline → multimer → inference
  mode: monomer
  pairing_strategy: all_vs_all

selection:
  left_group: plants
  right_group: pathogens
  query_name: P69B

resources:

  json_build:
    partition: short
    threads: 1

  data_pipeline:
    partition: short
    mem_mb: 64000
    runtime: 120
    threads: 8 

  inference:
    partition: short
    mem_mb: 64000
    runtime: 120
    threads: 8
    gpus: 1