# profiles/slurm/config.yaml

jobscript: "profiles/slurm/jobscript.sh"


jobs: 100


cluster: >
  sbatch
  --partition={resources.partition}
  --cpus-per-task={resources.cpus}
  --mem={resources.mem_mb}
  --time={resources.time}
  {('--gres=' + resources.gres) if hasattr(resources, 'gres') else ''}


default-resources:
  partition: short
  mem_mb: 2000
  time: "00:30:00"
  cpus: 1


printshellcmds: true
keep-going: true
rerun-incomplete: true
latency-wait: 60


max-jobs-per-second: 5
max-status-checks-per-second: 10


